//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text File|*.txt.
        /// </summary>
        internal static string File_Fileter_Txt {
            get {
                return ResourceManager.GetString("File_Fileter_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 36	3
        ///118.2381185	188.8888889	7952.380952
        ///118.2381185	188.8888889	7952.380952
        ///121.7330486	191.9753086	8256.17284
        ///108.9386442	181.7365269	8467.065868
        ///109.2212859	182.4712644	8727.011494
        ///109.8120107	191.8256131	8825.613079
        ///100.4227002	186.8556701	8992.268041
        ///123.8445558	231.5315315	10092.34234
        ///107.9198724	207.0993915	9847.870183
        ///110.3386151	191.0780669	9834.572491
        ///100.0272553	185.1851852	9234.567901
        ///100.1469051	196.4114833	9569.37799
        ///104.9209139	170.2987698	10094.90334
        ///99.17491749	151.8151815	103 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите файл с функциями.
        /// </summary>
        internal static string InputFileWithFunctions {
            get {
                return ResourceManager.GetString("InputFileWithFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите файл с переменными.
        /// </summary>
        internal static string InputFileWithVariables {
            get {
                return ResourceManager.GetString("InputFileWithVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении.
        /// </summary>
        internal static string ReadingError {
            get {
                return ResourceManager.GetString("ReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте другой файл
        ///.
        /// </summary>
        internal static string TryAnotherFile {
            get {
                return ResourceManager.GetString("TryAnotherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно открыть файл
        ///.
        /// </summary>
        internal static string UnnableToOpenFile {
            get {
                return ResourceManager.GetString("UnnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 36	5
        ///37.2	59.5	99.5	31.5	2505
        ///39.4	62.2	104.1	32.4	2675
        ///36.4	60.7	106.5	33.4	2828
        ///38.0	63.5	109.7	34.8	3037
        ///40.3	70.4	110.8	36.7	3239
        ///38.9	72.5	113.5	38.8	3489
        ///40.5	75	112.7	40.5	3740
        ///41.8	82.1	115.5	41.8	4000
        ///54.9	102.8	108.8	44.4	4481
        ///53.2	102.1	115.7	49.3	4855
        ///59.4	102.8	118.8	53.8	5291
        ///59.7	96.9	127.5	56.9	5744
        ///60.1	92	124	60.6	6262
        ///66.5	124.0	117.9	65.2	6968
        ///68.0	154.0	105.5	72.6	7682
        ///72.0	162.1	103.4	82.4	8421
        ///73.7	162.8	104.3	90.9	9243
        ///71.6	165.6	103.7	96.5	9724
        ///72.8	162.2	105.7	99 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
    }
}
